/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author WahyuSantoso
 */
public class MenuPesanana extends javax.swing.JFrame {

    /**
     * Creates new form MenuPesanana
     */
    
    private static final String stringDriver = "com.mysql.jdbc.Driver";
    private static final String stringConnection = "jdbc:mysql://localhost:3306/penjualan_rumah?user=root&password=";
    private static Connection cn = null;
    private static boolean statusConnection = false;
    private final int hargaTanah1 = 500000, hargaTanah2 = 600000, hargaTanah3 = 700000;
    private final int hargaBangunan1 = 90000000, hargaBangunan2 = 120000000, hargaBangunan3 = 150000000;
    private final int luasTanahAsli1 = 90, luasTanahAsli2 = 120, luasTanahAsli3 = 140;
    
    public MenuPesanana() {
        initComponents();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                closeMessage();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipeRumah = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        namaPemesan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hargaTanah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hargaBangunan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tipe36 = new javax.swing.JRadioButton();
        tipe45 = new javax.swing.JRadioButton();
        tipe54 = new javax.swing.JRadioButton();
        luasTanah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        luasTanahTersedia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jumlahCicilan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ppn = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cicilanPerBulan = new javax.swing.JTextField();
        konfirmasi = new javax.swing.JCheckBox();
        buttonProses = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        tampilData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga Tanah/m2");

        hargaTanah.setEditable(false);

        jLabel3.setText("Area");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Bougenvile", "Melati", "Flamboyan" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication/rumah_minimalis.jpg"))); // NOI18N

        jLabel5.setText("Harga Bangunan");

        hargaBangunan.setEditable(false);

        jLabel6.setText("Tipe Rumah");

        jLabel7.setText("Luas Tanah Asli");

        tipeRumah.add(tipe36);
        tipe36.setText("Tipe-36");
        tipe36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipe36ActionPerformed(evt);
            }
        });

        tipeRumah.add(tipe45);
        tipe45.setText("Tipe-45");
        tipe45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipe45ActionPerformed(evt);
            }
        });

        tipeRumah.add(tipe54);
        tipe54.setText("Tipe-54");
        tipe54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipe54ActionPerformed(evt);
            }
        });

        luasTanah.setEditable(false);

        jLabel8.setText("Luas Tanah Tersedia");

        luasTanahTersedia.setEditable(false);

        jLabel9.setText("Harga");

        harga.setEditable(false);

        jLabel10.setText("DP");

        jLabel11.setText("Lama Cicilan");

        jLabel12.setText("Bulan");

        jLabel13.setText("PPN (10%)");

        ppn.setEditable(false);

        jLabel14.setText("Cicilan/bln");

        cicilanPerBulan.setEditable(false);

        konfirmasi.setText("Setuju");
        konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasiActionPerformed(evt);
            }
        });

        buttonProses.setText("PROSES");
        buttonProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesActionPerformed(evt);
            }
        });

        buttonSimpan.setText("SIMPAN");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonClear.setText("CLEAR");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        tampilData.setText("Tampil Data Database");
        tampilData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaPemesan)
                            .addComponent(hargaTanah)
                            .addComponent(jComboBox1, 0, 161, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tampilData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonProses)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(buttonClear)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(tipe36)
                            .addComponent(tipe45)
                            .addComponent(tipe54)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(hargaBangunan)
                            .addComponent(luasTanah)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(luasTanahTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga)
                            .addComponent(dp)
                            .addComponent(jumlahCicilan)
                            .addComponent(ppn)
                            .addComponent(cicilanPerBulan, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(konfirmasi))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(namaPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(hargaBangunan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(hargaTanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tipe36)
                                .addComponent(luasTanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipe45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipe54))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(luasTanahTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(dp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jumlahCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(ppn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cicilanPerBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(konfirmasi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonProses)
                            .addComponent(buttonSimpan)
                            .addComponent(buttonClear)
                            .addComponent(tampilData)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMessage() {
        int inputType = JOptionPane.showConfirmDialog(null, "Konfirmasi keluar Aplikasi", "Dialog", JOptionPane.YES_NO_OPTION);
        if (inputType == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem() == "Bougenvile") {
            hargaTanah.setText(Integer.toString(hargaTanah1));
            hargaBangunan.setText(Integer.toString(hargaBangunan1));
        } else if (jComboBox1.getSelectedItem() == "Melati") {
            hargaTanah.setText(Integer.toString(hargaTanah2));
            hargaBangunan.setText(Integer.toString(hargaBangunan2));
        } else if (jComboBox1.getSelectedItem() == "Flamboyan") {
            hargaTanah.setText(Integer.toString(hargaTanah3));
            hargaBangunan.setText(Integer.toString(hargaBangunan3));
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void tipe36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipe36ActionPerformed
        // TODO add your handling code here:
        luasTanah.setText(Integer.toString(luasTanahAsli1));
        luasTanahTersedia.setText(Integer.toString(luasTanahAsli1));
        
        int valueLuasTanahTersedia = Integer.parseInt(luasTanah.getText());
        int valueHargaTanah = Integer.parseInt(hargaTanah.getText());
        int valueHargaBagunan = Integer.parseInt(hargaBangunan.getText());
        harga.setText(Integer.toString(valueLuasTanahTersedia * valueHargaTanah + valueHargaBagunan));
    }//GEN-LAST:event_tipe36ActionPerformed

    private void tipe45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipe45ActionPerformed
        // TODO add your handling code here:
        luasTanah.setText(Integer.toString(luasTanahAsli2));
        luasTanahTersedia.setText(Integer.toString(luasTanahAsli2));
        
        int valueLuasTanahTersedia = Integer.parseInt(luasTanah.getText());
        int valueHargaTanah = Integer.parseInt(hargaTanah.getText());
        int valueHargaBagunan = Integer.parseInt(hargaBangunan.getText());
        harga.setText(Integer.toString(valueLuasTanahTersedia * valueHargaTanah + valueHargaBagunan));
    }//GEN-LAST:event_tipe45ActionPerformed

    private void tipe54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipe54ActionPerformed
        // TODO add your handling code here:
        luasTanah.setText(Integer.toString(luasTanahAsli3));
        luasTanahTersedia.setText(Integer.toString(luasTanahAsli3));
        
        int valueLuasTanahTersedia = Integer.parseInt(luasTanah.getText());
        int valueHargaTanah = Integer.parseInt(hargaTanah.getText());
        int valueHargaBagunan = Integer.parseInt(hargaBangunan.getText());
        harga.setText(Integer.toString(valueLuasTanahTersedia * valueHargaTanah + valueHargaBagunan));
    }//GEN-LAST:event_tipe54ActionPerformed

    private void buttonProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesActionPerformed
        // TODO add your handling code here:
        
        int valueHarga = Integer.parseInt(harga.getText());
        int valuePPN = ((10*valueHarga)/100);
        ppn.setText(Integer.toString(valuePPN));
        
        int valueCicilan = (valueHarga + Integer.parseInt(ppn.getText()) - Integer.parseInt(dp.getText())) / Integer.parseInt(jumlahCicilan.getText());
        cicilanPerBulan.setText(Integer.toString(valueCicilan));
    }//GEN-LAST:event_buttonProsesActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        String valueTipeRumah = null;
        if (tipe36.isSelected()) {
            valueTipeRumah = "T-36";
        } else if (tipe45.isSelected()) {
            valueTipeRumah = "T-45";
        } else if (tipe54.isSelected()) {
            valueTipeRumah = "T-54";
        }
        
        
        if (statusConnection) {
            try {
                cn = DriverManager.getConnection(stringConnection);
                Statement sta = cn.createStatement();
                sta.executeUpdate("INSERT into data values('"+namaPemesan.getText()+"', '"+jComboBox1.getSelectedItem()+"', '"+valueTipeRumah+"', '"+Integer.parseInt(luasTanah.getText())+"', '"+Integer.parseInt(harga.getText())+"', '"+Integer.parseInt(jumlahCicilan.getText())+"', '"+Integer.parseInt(cicilanPerBulan.getText())+"')");
                JOptionPane.showMessageDialog(null, "Data disimpan ke database");
                cn.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "kesalahan koneksi database\n"+e);
            }
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:
        namaPemesan.setText("");
        hargaTanah.setText("");
        jComboBox1.setSelectedItem("Pilih");
        hargaBangunan.setText("");
        luasTanah.setText("");
        luasTanahTersedia.setText("");
        harga.setText("");
        dp.setText("");
        jumlahCicilan.setText("");
        ppn.setText("");
        cicilanPerBulan.setText("");
    }//GEN-LAST:event_buttonClearActionPerformed

    private void konfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasiActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "PELANGGAN KONFIRMASI/SETUJU");
    }//GEN-LAST:event_konfirmasiActionPerformed

    private void tampilDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilDataActionPerformed
        // TODO add your handling code here:
        MenuTampilData move = new MenuTampilData();
        move.setVisible(true);
    }//GEN-LAST:event_tampilDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPesanana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPesanana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPesanana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPesanana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        try {
            Class.forName(stringDriver);
            statusConnection = true;
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "terjadi kesalahan driver\n" + e);
        }
        
        if (statusConnection) {
            try {
                cn = DriverManager.getConnection(stringConnection);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "kesalahan koneksi database\n" + e);
            }
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPesanana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonProses;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JTextField cicilanPerBulan;
    private javax.swing.JTextField dp;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField hargaBangunan;
    private javax.swing.JTextField hargaTanah;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jumlahCicilan;
    private javax.swing.JCheckBox konfirmasi;
    private javax.swing.JTextField luasTanah;
    private javax.swing.JTextField luasTanahTersedia;
    private javax.swing.JTextField namaPemesan;
    private javax.swing.JTextField ppn;
    private javax.swing.JButton tampilData;
    private javax.swing.JRadioButton tipe36;
    private javax.swing.JRadioButton tipe45;
    private javax.swing.JRadioButton tipe54;
    private javax.swing.ButtonGroup tipeRumah;
    // End of variables declaration//GEN-END:variables
}
